### ISSUE TITLE
failed install hook when keyserver.ubuntu.com is not reachable

### ISSUE THREAD

**Issue by jamesbeedy** [omnivector-solutions/slurm-charms#111]
The slurm charms error on install when keyserver.ubuntu.com is not reachable.

**To Reproduce**
Deploy the slurm charms in an environment where keyserver.ubuntu.com is not reachable.

**Expected behavior**
I would expect the installation to fail in this scenario.

I have addressed this issue by providing the gpg in files inside the `templates/` dir in [slurm-ops-manager](https://github.com/omnivector-solutions/slurm-ops-manager/pull/66/files).

**Comment by heitorPB** [comment]
fixed in #110
